// <auto-generated />
namespace klukk_social.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class lagauser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lagauser));
        
        string IMigrationMetadata.Id
        {
            get { return "201505062253041_laga user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
