// <auto-generated />
namespace klukk_social.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class groups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(groups));
        
        string IMigrationMetadata.Id
        {
            get { return "201505131239213_groups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
